### PR TITLE
Add --local-version and --force-local-version flags

### PR DESCRIPTION
**Pull request by fredemmott**
The idea here is to allow config-file-free installations, without requiring that all future versions use the same detection method.

- `--local-version` is intended for coding into programs that launch the updater manually (i.e. no scheduled job); if a config file specifies a version, this takes precedence
- `--force-local-version` takes precedence over the configuration files; this is intended for manually testing/fixing stuff

'FixedVersion' can also be specified in configuration files, presumably only local config files.

### CODE REVIEW

**Comment by fredemmott** [comment]
Tested with OpenXR-API-Layers-GUI with this config:

```
	"shared": {
		"detectionMethod": "FixedVersion",
		"detection": "9999.99.99"
	},
```

- No update.
- No change if I use `--local-version=1.2.3`
- Does have update if I use `--force-local-version=1.2.3.4`

Then deleted config file.
- error about no version detected if I don't use either arg
- either arg works for specifying a version

**Comment by nefarius** [comment]
Reminder for me to [update in docs](https://docs.nefarius.at/projects/Vicius/Command-Line-Arguments/).

**Comment by nefarius** [comment]
[Product detection](https://docs.nefarius.at/projects/Vicius/Product-Detection/) article also needs to be updated to cover new method.

**Comment by nefarius** [comment]
I changed the schema to comply better with JSON (de-)serilizers.

**Pull request merged**
